# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
#  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "data-server.luopc.com:9093"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "example_rules.yaml"
# - "first_rules.yml"
# - "second_rules.yml"

#remote_write: # 存储到远程VM存储
#  - url: http://data-server.luopc.com:8428/api/v1/write
#    queue_config: # 如果Prometheus抓取指标很大，可以加调整queue，但是会提高内存占用
#      max_samples_per_send: 10000
#      capacity: 20000
#      max_shards: 30

##
### Promxy configuration
##
promxy:
  server_groups:
    # All upstream prometheus service discovery mechanisms are supported with the same
    # markup, all defined in https://github.com/prometheus/prometheus/blob/master/discovery/config/config.go#L33
    - static_configs:
        - targets:
            - data-server.luopc.com:8428
      # labels to be added to metrics retrieved from this server_group
      labels:
        sg: vm_8428
      # anti-affinity for merging values in timeseries between hosts in the server_group
      anti_affinity: 10s
      # time to wait for a server's response headers after fully writing the request (including its body, if any).
      # This time does not include the time to read the response body.
      timeout: 5s
      # Controls whether to use remote_read or the prom API for fetching remote RAW data (e.g. matrix selectors)
      # Note, some prometheus implementations (e.g. [VictoriaMetrics](https://github.com/prometheus/prometheus/issues/4456) don't support remote_read.
      # remote_read: true
      # configures the path to send remote read requests to. The default is "api/v1/read"
      # remote_read_path: api/v1/read
      # path_prefix defines a prefix to prepend to all queries to hosts in this servergroup
      # This can be relabeled using __path_prefix__
      # path_prefix: /promxy
      # query_params adds the following map of query parameters to downstream requests.
      # The initial use-case for this is to add `nocache=1` to VictoriaMetrics downstreams
      # (see https://github.com/jacksontj/promxy/issues/202)
      query_params:
        nocache: 1
      # configures the protocol scheme used for requests. Defaults to http
      scheme: http
      # options for promxy's HTTP client when talking to hosts in server_groups
      http_client:
        # dial_timeout controls how long promxy will wait for a connection to the downstream
        # the default is 200ms.
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true
